### PR TITLE
Support blaze-markup-0.8

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by ndmitchell** [comment]
It would be great for this to be released and uploaded to hackage/stackage since it's a very handy library. Ping @byorgey who uploaded the last few versions.

**Comment by byorgey** [comment]
Sure, I'll merge and upload soon.

**Comment by byorgey** [comment]
LGTM, thanks.  Uploaded to Hackage as `blaze-svg-0.3.6.1`.

**Comment by phadej** [comment]
@byorgey thanks!

**Pull request merged**
